import { Habit } from "./types";


export const HABITS: Habit[] = [
  { id: "1",  name: "Working Out", emoji: "💪", isCustomHabit: false, isPositive: true },
  { id: "2",  name: "Reading", emoji: "📖", isCustomHabit: false, isPositive: true },
  { id: "3",  name: "Meditation", emoji: "🧘", isCustomHabit: false, isPositive: true },
  { id: "4",  name: "Journaling", emoji: "📝", isCustomHabit: false, isPositive: true },
  { id: "5",  name: "Healthy Eating", emoji: "🥗", isCustomHabit: false, isPositive: true },
  { id: "6",  name: "Walking", emoji: "🚶", isCustomHabit: false, isPositive: true },
  { id: "7",  name: "Yoga", emoji: "🧘‍♀️", isCustomHabit: false, isPositive: true },
  { id: "8",  name: "Drinking Water", emoji: "💧", isCustomHabit: false, isPositive: true },
  { id: "9",  name: "Stretching", emoji: "🤸", isCustomHabit: false, isPositive: true },
  { id: "10", name: "Learning New Skill", emoji: "🎓", isCustomHabit: false, isPositive: true },
  { id: "11", name: "Running", emoji: "🏃", isCustomHabit: false, isPositive: true },
  { id: "12", name: "Cooking", emoji: "👩‍🍳", isCustomHabit: false, isPositive: true },
  { id: "13", name: "Gardening", emoji: "🌱", isCustomHabit: false, isPositive: true },
  { id: "14", name: "Cleaning", emoji: "🧹", isCustomHabit: false, isPositive: true },
  { id: "15", name: "Practicing Music", emoji: "🎸", isCustomHabit: false, isPositive: true },
  { id: "16", name: "Walking Dog", emoji: "🐕", isCustomHabit: false, isPositive: true },
  { id: "17", name: "Painting", emoji: "🎨", isCustomHabit: false, isPositive: true },
  { id: "18", name: "Volunteering", emoji: "🤝", isCustomHabit: false, isPositive: true },
  { id: "19", name: "Flossing", emoji: "🦷", isCustomHabit: false, isPositive: true },
  { id: "20", name: "Skincare", emoji: "🧴", isCustomHabit: false, isPositive: true },
  { id: "21", name: "Planning Day", emoji: "📅", isCustomHabit: false, isPositive: true },
  { id: "22", name: "Saving Money", emoji: "💰", isCustomHabit: false, isPositive: true },
  { id: "23", name: "Stretching Break", emoji: "🧎", isCustomHabit: false, isPositive: true },
  { id: "24", name: "Breathing Exercises", emoji: "🌬️", isCustomHabit: false, isPositive: true },
  { id: "25", name: "Positive Affirmations", emoji: "💭", isCustomHabit: false, isPositive: true },
  { id: "26", name: "Listening to Music", emoji: "🎵", isCustomHabit: false, isPositive: true },
  { id: "27", name: "Cold Shower", emoji: "🚿", isCustomHabit: false, isPositive: true },
  { id: "28", name: "Early Wake Up", emoji: "⏰", isCustomHabit: false, isPositive: true },
  { id: "29", name: "Evening Walk", emoji: "🌆", isCustomHabit: false, isPositive: true },
  { id: "30", name: "Stretching in Morning", emoji: "🤸‍♂️", isCustomHabit: false, isPositive: true },
  { id: "31", name: "Call a Friend", emoji: "📞", isCustomHabit: false, isPositive: true },
  { id: "32", name: "Mindful Eating", emoji: "🥢", isCustomHabit: false, isPositive: true },
  { id: "33", name: "Drink Herbal Tea", emoji: "🍵", isCustomHabit: false, isPositive: true },
  { id: "34", name: "Cycling", emoji: "🚴", isCustomHabit: false, isPositive: true },
  { id: "35", name: "Writing Poetry", emoji: "✒️", isCustomHabit: false, isPositive: true },
  { id: "36", name: "Stretching Before Sleep", emoji: "🛌", isCustomHabit: false, isPositive: true },
  { id: "37", name: "Meditation Before Bed", emoji: "🕯️", isCustomHabit: false, isPositive: true },
  { id: "38", name: "Practice Language", emoji: "🗣️", isCustomHabit: false, isPositive: true },
  { id: "39", name: "Declutter Room", emoji: "🗑️", isCustomHabit: false, isPositive: true },
  { id: "40", name: "Read News", emoji: "📰", isCustomHabit: false, isPositive: true },
  { id: "41", name: "Limit Sugar Intake", emoji: "🍬", isCustomHabit: false, isPositive: true },
  { id: "42", name: "Take Vitamins", emoji: "💊", isCustomHabit: false, isPositive: true },
  { id: "43", name: "Practice Gratitude", emoji: "🙏", isCustomHabit: false, isPositive: true },
  { id: "44", name: "Call Family", emoji: "👪", isCustomHabit: false, isPositive: true },
  { id: "45", name: "Take a Nap", emoji: "😴", isCustomHabit: false, isPositive: true },
  { id: "46", name: "Stretch Between Work", emoji: "💺", isCustomHabit: false, isPositive: true },
  { id: "47", name: "Hydrate Often", emoji: "💦", isCustomHabit: false, isPositive: true },
  { id: "48", name: "Practice Mindfulness", emoji: "🧘‍♂️", isCustomHabit: false, isPositive: true },
  { id: "49", name: "Smile Often", emoji: "😊", isCustomHabit: false, isPositive: true },
  { id: "50", name: "Compliment Someone", emoji: "🌸", isCustomHabit: false, isPositive: true },

  { id: "51",  name: "Doomscrolling", emoji: "📱", isCustomHabit: false, isPositive: false },
  { id: "52",  name: "Overeating Junk", emoji: "🍔", isCustomHabit: false, isPositive: false },
  { id: "53",  name: "Skipping Sleep", emoji: "😴", isCustomHabit: false, isPositive: false },
  { id: "54",  name: "Procrastinating", emoji: "⏳", isCustomHabit: false, isPositive: false },
  { id: "55",  name: "Excessive Social Media", emoji: "📱", isCustomHabit: false, isPositive: false },
  { id: "56",  name: "Smoking", emoji: "🚬", isCustomHabit: false, isPositive: false },
  { id: "57",  name: "Drinking Alcohol", emoji: "🍷", isCustomHabit: false, isPositive: false },
  { id: "58",  name: "Biting Nails", emoji: "💅", isCustomHabit: false, isPositive: false },
  { id: "59",  name: "Skipping Meals", emoji: "🍽️", isCustomHabit: false, isPositive: false },
  { id: "60",  name: "Watching Too Much TV", emoji: "📺", isCustomHabit: false, isPositive: false },
  { id: "61",  name: "Overthinking", emoji: "💭", isCustomHabit: false, isPositive: false },
  { id: "62",  name: "Overusing Phone", emoji: "📱", isCustomHabit: false, isPositive: false },
  { id: "63",  name: "Ignoring Exercise", emoji: "🛋️", isCustomHabit: false, isPositive: false },
  { id: "64",  name: "Skipping Workouts", emoji: "🏋️‍♂️", isCustomHabit: false, isPositive: false },
  { id: "65",  name: "Eating Late", emoji: "🌙", isCustomHabit: false, isPositive: false },
  { id: "66",  name: "Impulse Buying", emoji: "🛒", isCustomHabit: false, isPositive: false },
  { id: "67",  name: "Gossiping", emoji: "🗣️", isCustomHabit: false, isPositive: false },
  { id: "68",  name: "Skipping Hydration", emoji: "🥤", isCustomHabit: false, isPositive: false },
  { id: "69",  name: "Staying Up Late", emoji: "🌜", isCustomHabit: false, isPositive: false },
  { id: "70",  name: "Mindless Snacking", emoji: "🍫", isCustomHabit: false, isPositive: false },
  { id: "71",  name: "Overchecking Email", emoji: "📧", isCustomHabit: false, isPositive: false },
  { id: "72",  name: "Excessive Gaming", emoji: "🎮", isCustomHabit: false, isPositive: false },
  { id: "73",  name: "Skipping Hygiene", emoji: "🛁", isCustomHabit: false, isPositive: false },
  { id: "74",  name: "Watching Social Media Stories", emoji: "📲", isCustomHabit: false, isPositive: false },
  { id: "75",  name: "Complaining Often", emoji: "😤", isCustomHabit: false, isPositive: false },
  { id: "76",  name: "Being Late", emoji: "⏰", isCustomHabit: false, isPositive: false },
  { id: "77",  name: "Skipping Reading", emoji: "📚", isCustomHabit: false, isPositive: false },
  { id: "78",  name: "Lying", emoji: "🤥", isCustomHabit: false, isPositive: false },
  { id: "79",  name: "Being Impatient", emoji: "⌛", isCustomHabit: false, isPositive: false },
  { id: "80",  name: "Ignoring Family", emoji: "👪", isCustomHabit: false, isPositive: false },
  { id: "81",  name: "Overconsuming Caffeine", emoji: "☕", isCustomHabit: false, isPositive: false },
  { id: "82",  name: "Skipping Meditation", emoji: "🧘‍♀️", isCustomHabit: false, isPositive: false },
  { id: "83",  name: "Overspending", emoji: "💳", isCustomHabit: false, isPositive: false },
  { id: "84",  name: "Being Negative", emoji: "😒", isCustomHabit: false, isPositive: false },
  { id: "85",  name: "Overwatching Videos", emoji: "🎬", isCustomHabit: false, isPositive: false },
  { id: "86",  name: "Interrupting Others", emoji: "🙅", isCustomHabit: false, isPositive: false },
  { id: "87",  name: "Skipping Appointments", emoji: "📅", isCustomHabit: false, isPositive: false },
  { id: "88",  name: "Overeating Sweets", emoji: "🍭", isCustomHabit: false, isPositive: false },
  { id: "89",  name: "Excessive TV Binge", emoji: "📺", isCustomHabit: false, isPositive: false },
  { id: "90",  name: "Scrolling in Bed", emoji: "🛏️📱", isCustomHabit: false, isPositive: false },
  { id: "91",  name: "Skipping Breakfast", emoji: "🥐", isCustomHabit: false, isPositive: false },
  { id: "92",  name: "Procrastinating Tasks", emoji: "📝", isCustomHabit: false, isPositive: false },
  { id: "93",  name: "Overchecking Notifications", emoji: "🔔", isCustomHabit: false, isPositive: false },
  { id: "94",  name: "Complaining About Work", emoji: "💼", isCustomHabit: false, isPositive: false },
  { id: "95",  name: "Overusing Phone Camera", emoji: "📸", isCustomHabit: false, isPositive: false },
  { id: "96",  name: "Skipping Lunch", emoji: "🥗", isCustomHabit: false, isPositive: false },
  { id: "97",  name: "Excessive Snacking", emoji: "🍪", isCustomHabit: false, isPositive: false },
  { id: "98",  name: "Overdrinking Soda", emoji: "🥤", isCustomHabit: false, isPositive: false },
  { id: "99",  name: "Being Rude Online", emoji: "💻", isCustomHabit: false, isPositive: false },
  { id: "100", name: "Oversleeping", emoji: "🛌", isCustomHabit: false, isPositive: false },
];
